local ashaar = {
	-- Dagh Dehlvi
	Dagh_Dehlvi = {
		"tumhara dil mire dil ke barabar ho nahin sakta : vo shisha ho nahi sakta ye patthar ho nahin sakta",
		"hazaron kaam mohabbat in hain maze ke 'dagh' : jo log kuchh nahin karte kamal karte hain",
		"vafa karenge nibahebge baat manenge : tumhen bhi yaad hai kuchh ye kalam kis ka tha",
		"sab log jidhar vo hain udhar dekh rahe hain : ham dekhne valon ki nazar dekh rahe hain",
		"milate ho usi ko khaak in jo dil se milta hai : miri jaan chahne vaala baDi mushkil se milta hai",
		"aa.ina dekh ke kahte hain sabvarne vaale : aaj be-maut marenge mire marne vaale",
		"hain hai shauq ki be-parda tum ko dekhebge : tumhen hai sharm to ankhon pe haath dhar lena",
		"tumhara hi mushtaq-e-didar hoga : gaya jaan se ik javan aate aate",
		"is nahin ka koi ilaaj nahi : roz kahte hain aap aaj nahin",
		"ashiqi se milega ai zahid : bandagi se khuda nahin milta",
		"ghazab kiya tire va.ade pe e'tibar kiya : tamam raat qayamat ka intizar kiya",
		"lipaT jaate hain vo bijli ke Dar se : ilahi ye ghaTa do din to barse",
		"khuub parda hai ki chilman se lage baiThe hain : saaf chhupte bhi nahi samne aate bhi nahin",
		"hijr in zahr kha ke mar ja.ub : maut ka intizar kaun kare",
		"le chala jaan miri ruuTh ke jaana tera : aise aane se to behtar tha na aana tera",
		"zid har ik baat par nahin achchhi : dost ki dost maan lete hain",
		"na jaana ki duniya se jaata hai koi : bahut der ki hrban aate aate",
		"chale aate hain dil b arman lakhon : makan bhar gaya mehman aate aate",
		"nahin khel ai 'dagh' yarob se kah do : ki aati hai urdu zaban aate aate",
		"shab-e-visal hai gul kar do in charaghon ko : khushi ki bazm b kya kaam jalne valon ka",
		"aap ka e'tibar kaun kare : roz ka intizar kaun kare",
		"hazar baar jo manga karo to kya hasil : dua vahi hai jo dil se kabhi nikalti hai",
		"lutf-e-mai tujh se kya kahun zahid : haa.e kam-bakht tu ne pi hi nahi",
		"rukh-e-raushan ke aage sham.a rakh kar vo ye kahte hain : udhar jaata hai dekheb ya idhar parvana aata hai",
		"saqiya tishnagi ki taab nahin : zahr de de agar sharab nahi",
		"falak deta hai jin ko aish un ko gham bhi hote hain : jahab bajte hain naqqare vahan matam bhi hota hai",
		"tum ko chaha to khata kya hai bata do mujh ko : dusra koi to apna sa dikha do mujh ko",
	},
	-- Mirza Ghalib
	Ghalib = {
		"ham ko ma.alum hai jannat ki haqiqat lekin : dil ke khush rakhne ko 'ghalib' ye khayal achchha hai",
		"karne ga.e the us se taghaful ka ham gila : ki ek hi nigah ki bas khaak ho ga.e",
		"ishq ne 'ghalib' nikamma kar diya : varna ham bhi aadmi the kaam ke",
		"is sadgi pe kaun na mar jaa.e ai khuda : laDte hain aur haath b talvar bhi nahin",
		"mohabbat in nahi hai farq jiine aur marne ka : usi ko dekh kar jiite hain jis kafir pe dam nikle ",
		"main bhi mubh in zaban rakhta huun : kaash puchho ki mudda.a kya hai",
		"hazaron khvahisheb aisi ki har khvahish pe dam nikle : bahut nikle mire arman lekin phir bhi kam nikle",
		"un ke dekhe se jo aa jaati hai munh par raunaq : vo samajhte hain ki bimar ka haal achch hai",
		"ye na thi hamari qismat ki visal-e-yar hota : agar aur jiite rahte yahi intizar hota",
		"ragon b dauDte phirne ke ham nahin qaa.il : jab aankh hi se na Tapka to phir lahu kya hai",
		"ishq par zor nahin hai ye vo atish 'ghalib' : ki laga.e na lage aur bujha.e na bane",
		"vo aa.e ghar in hamare khuda ki qudrat hai : kabhi ham un ko kabhi apne ghar ko dekhte hain",
		"ishrat-e-qatra hai dariya in fana ho jaana : dard ka had se guzarna hai dava ho jaana",
		"na tha kuchh to khuda tha kuchh na hota to khuda hota : Duboya mujh ko hone ne na hota main to kya hota",
		"dil hi to hai na sang-o-khisht dard se bhar na aa.e kyuub : ro.enge ham hazaar baar koi hain sata.e kyuun",
		"bas-ki dushvar hai har kaam ka asan hona : aadmi ko bhi muyassar nahi insan hona ",
		"be-khudi be-sabab nahin 'ghalib' : kuchh to hai jis ki parda-dari hai",
		"ranj se khugar hua insab to miT jaata hai ranj : mushkilen mujh par paDin itni ki asan ho ga.iin",
		"ham ko un se vafa ki hai ummid : jo nahin jante vafa kya hai",
		"hain aur bhi duniya b sukhan-var bahut achchhe : kahte hain ki 'ghalib' ka hai andaz-e-bayan aur",
		"rekhte ke tumhin ustad nahi ho 'ghalib' : kahte hain agle zamane in koi 'meer' bhi tha",
		"aaeena kyuun na duun ki tamasha kahen jise : aisa kahan se la.un ki tujh sa kahen jise",
		"ishq se tabi.at ne ziist ka maza paaya : dard ki dava paa.i dard-e-be-dava paaya",
	},
	-- Meer Taqi Meer
	Meer = {
		"rah-e-dur-e-ishq in rota hai kya : aage aage dekhiye hota hai kya",
		"patta patta buuTa buuTa haal hamara jaane hai : jaane na jaane gul hi na jaane baagh to saara jaane hai",
		"hoga kisi divar ke saa.e in paDa 'meer' : kya rabt mohabbat se us aram-talab ko",
		"mat sahl hain jaano phirta hai falak barsob : tab khaak ke parde se insan nikalte hain",
		"nazuki us ke lab ki kya kahiye : pankhuDi ik gulab ki si hai",
		"'meer' ham mil ke bahut khush hue tum se pyare : is kharabe b miri jaan tum abad raho",
		"ahd-e-javani ro ro kaaTa piiri b li ankhein muund : yaani raat bahut the jaage subah hui aram kiya",
		"mujhe kaam rone se aksar hai naseh : tu kab tak mire mubh ko dhota rahega",
		"'meer' un nim-baz abkhon in : saari masti sharab ki si hai",
		"ishq ik 'meer' bhari patthar hai : kab ye tujh na-tavan se uThta hai",
		"shaam se kuchh bujha sa rahta huun : dil hua hai charagh muflis ka",
		"dekh to dil ki jaab se uThta hai : ye ddhua sa kahan se uThta hai",
		"kaash us ke ru-ba-ru na kareb mujh ko hashr in : kitne mire saval hain jin ka nahin javab",
		"ishq in ji ko sabr-o-taab kahab : uss se ankhein laDin to khvab kahan",
		"padhte phirebge galiyon in in rekhton ko log : muddat rahengi yaad ye baten hamariyan",
		"'meer' bandon se kaam kab nikla : mabgna hai jo kuchh khuda se maang",
		"tujh ko masjid hai mujh ko mai-khana : vaaiyz apni apni qismat hai",
		"tha sab ko da.ava ishq ka lekin na Thehra koi bhi : danista apni jaan se dil ko uThaya ek maib",
		"'meer' sahab tum farishta ho to ho : aadmi hona to mushkil hai miyan",
		"yahi jaana ki kuchh na jaana haa.e : so bhi ik umr in hua ma`lum",
		"jaise bijli ke chamakne se kisi ki sudh jaae : be-khudi aa.i achanak tire aa jaane se",
		"surma jo nuur bakhshe hai abkhon ko khalq ki : shayad ki rah-e-yar ki hi khaak dhuul ho",
		"kaam the ishq b bahut par 'meer' : ham hi farigh hue shitabi se",
		"hosh jaata nahin raha lekin : jab vo aata hai tab nahin aata",
		"dilli in aaj bhiik bhi milti nahi unhen : tha kal talak dimagh jinhen taj-o-takht ka",
		"ab jo ik hasrat-e-javani hai : umr-e-rafta ki ye nishani hai",
	},
	-- Parveen Shakir
	Parveen_Shakir = {
		"vo na aaega hain ma.alum tha is shaam bhi : intizar us ka magar kuchh soch kar karte rahe",
		"kuchh to hava bhi sard thi kuchh tha tira khayal bh : dil ko khushi ke saath saath hota raha malal bhi",
		"ri talab tha ek shakhs vo jo nahin mila to phir : haath dua se yuun gira bhuul gaya saval bhi",
		"ghar aap hi jagmaga uThega : dahliz pe ik qadam bahut hai",
		"ye hava kaise uDa le gai anchal ra : yuun satane ki to aadat mire ghanshyam ki thi",
		"sukuut-e-shahr-e-sukhan in vo phuul sa lahja : samaaton ki faza khvab khvab kar dega",
		"shaam ki na-samajh hava puchh rahi hai ik pata : mauj-e-hava-e-ku-e-yar kuchh to mira khayal bhi",
		"kaanp uThti huun main ye soch ke tanhai in : mere chehre pe tira naam na paDh le koi",
		"kuchh to tire mausam hi mujhe raas kam aae : aur kuchh miri miTTi in baghavat bhi bahut thi",
		"baat vo aadhi raat ki raat vo puure chand ki : chand bhi ain chait ka us pe tira jamal bhi",
		"husn ke samajhne ko umr chahiye janan : do ghaDi ki chahat in laDkiyan nahin khultin",
		"raste in mil gaya to sharik-e-safar na jaan : jo chhanv mehrban ho use apna ghar na jaan",
		"vo to khush-bu hai havao b bikhar jaega : masla phool ka hai phuul kidhar jaega",
		"kuchh faisla to ho ki kidhar jaana chahiye : paani ko ab to sar se guzar jaana chahiye",
		"kaise kah duun ki mujhe chhoD diya hai us ne : baat to sach hai magar baat hai rusvai ki",
		"aks-e-khushbu huun bikharne se na roke koi : aur bikhar jaun to mujh ko na sameTe koi",
		"apne qatil ki zehanat se pareshan huun main : roz ik maut naye tarz ki ijad kare",
		"main sach kahungi magar phir bhi haar jaungi : wo jhuT bolega aur la-jawab kar dega",
		"dene vaale ki mashiyyat pe hai sab kuchh mauquf : mangne vaale ki hajat nahin dekhi jaati",
		"mumkina faislon in ek hijr ka faisla bhi tha : ham ne to ek baat ki us ne kamal kar diya",
		"haath re bhuul baiThe dastaken dene ka fan : band mujh par jab se us ke ghar ka darvaza hua",
		"vaqt-e-rukhsat aa gaya dil phir bhi ghabraya nahin : us ko ham kya kho.enge jis ko kabhi paaya nahin",
		"tere paimane in gardish nahin baaqi saaqi : aur tiri bazm se ab koi uTha chahta hai",
		"tere tohfe to sab achchhe hain magar mauj-e-bahar : ab ke re liye khushbu-e-hina aai ho",
	},
	-- Jaun Eliya
	Jaun_Eliya = {
		"bahut nazdik aati ja rahi ho : bichhaDne ka irada kar liya kya",
		"shaam hi se dukan-e-did hai band : nahin nuqsan tak dukan in kya",
		"yaaro kuchh to zikr karo tum us ki qayamat banhon ka : vo jo simaTte honge un in vo to mar jaate honge",
		"umr guzregi imtihan in kya : daagh hi denge mujh ko daan mein kya",
		"ri har baat be-asar hi rahi : nuqs hai kuchh mire bayan mein kya",
		"aur to kya tha bechne ke liye : apni ankhon ke khvab beche hain",
		"vo mile to ye puchhna hai mujhe : ab bhi huun main tiri amaan in kya",
		"main bhi bahut ajiib huun itna ajiib huun ki bas : khud ko tabah kar liya aur malal bhi nahin",
		"kya sitam hai ki ab tiri surat : ghaur karne pe yaad aati hai ",
		"kis liye dekhti ho a.ina : tum to khud se bhi khubsurat ho",
		"yuun jo takta hai asman ko tu : koi rahta hai asman in kya",
		"mustaqil bolta hi rahta huun : kitna khamosh huun main andar se",
		"us gali ne ye sun ke sabr kiya : jaane vaale yahan ke the hi nahin",
		"aaj mujh ko bahut bura kah kar : aap ne naam to liya ra",
		"jurm in ham kami karen bhi to kyuun : tum saza bhi to kam nahin karte",
		"tumhara hijr mana luun agar ijazat ho : main dil kisi se laga luun agar ijazat ho",
		"bin tumhare kabhi nahin aa.i : kya miri niind bhi tumhari hai",
		"sochta huun ki us ki yaad akhir : ab kise raat bhar jagati hai",
		"zindagi kya hai ik kahani hai : ye kahani nahin sunani hai",
		"zindagi ek fan hai lamhon ko : apne andaz se ganvane ka",
		"ab miri koi zindagi hi nahin : ab bhi tum ri zindagi ho kya",
		"naya ik rishta paida kyuun karen ham : bichhaDna hai to jhagDa kyuun karen ham",
		"kaam ki baat main ne ki hi nahin : ye mira taur-e-zindagi hi nahin",
		"shauq hai is dil-e-darinda ko : aap ke honT kaaT khane ka",
		"apne sar ik bala to leni thi : main ne vo zulf apne sar li hai",
		"mil rahi ho baDe tapak ke saath : mujh ko yaksar bhula chuki ho kya",
	},
	-- Javed Akhtar
	Javed_Akhtar = {
		"ghalat baton ko khamoshi se sunna haami bhar lena : bahut hain fa.ede is in magar achchha nahin lagta",
		"jidhar jaate hain sab jaana udhar achchha nahin lagta : mujhe pamal raston ka safar achchha nahin lagta",
		"mujhe dushman se bhi khuddari ki ummid rahti hai : kisi ka bhi ho sar qadmon in sar achchha nahin lagta",
		"tab ham donon vaqt chura kar laate the : ab milte hain jab bhi fursat hoti hai",
		"yaad use bhi ek adhūra afsana to hoga : kal raste in us ne ham ko pahchana to hoga",
		"ūnchi imaraton se makan ra ghir gaya : kuchh log mere hisse ka sūraj bhi kha ga.e",
		"aql ye kahti hai duniya milti hai bazar in : dil magar ye kahta hai kuchh aur behtar dekhiye",
		"har taraf shor usi naam ka hai duniya in : koi us ko jo pukare to pukare kaise",
		"yahi halat ibtida se rahe : log ham se khafa khafa se rahe",
		"is shahr in jiine ke andaz nirale hain : honTon pe latife hain avaz mein chhale hain",
		"tum ye kahte ho ki main ghair huun phir bhi shayad : nikal aa.e koi pahchan zara dekh to lo",
		"main pa saka na kabhi is khalish se chhuTkara : vo mujh se jiit bhi sakta tha jaane kyuun haara",
		"tum baiThe ho lekin jaate dekh raha huun : main tanha.i ke din aate dekh raha huun ",
		"us ke bandon ko dekh kar kahiye : ham ko ummid kya khuda se rahe",
		"ek ye din jab apnon ne bhi ham se naata toḌ liya : ek vo din jab peḌ ki shakhen bojh hamara sahti thiin",
	},
	-- Allama Iqbal
	Allama_Iqbal = {
		"khuda ne aaj tak us qaum ki halat nahin badli : na ho jis ko khayal aap apni halat badalne ka",
		"sitaron se age jahan aur bhi hain : abhi ishq ke imtihan aur bhi hain",
		"nahin tira nashe-man qasr-e-sultani ke gumbad par : tu shahbaz hai parvaz hai kaam tera",
		"shikvah-e-zulmat-e-shab se to kahin behtar tha : apne hisse ki koi sham.a jalate jaate",
		"khudi ko kar buland itna ki har taqdir se pahle : khuda bande se khud puuchhe bata teri raza kya hai",
		"ye kaa.inat abhi naa-tamam hai shayad : ki aa rahi hai damadam sada-e-kun fa-yakuun",
		"vatan ki fikr kar nadan museebat aane vaali hai : tiri barbadiyon ke mashve hain asman in",
		"agar ho zauq-e-talab to fursat-e-kam-yaab pe bhi : kar guzar ai be-khabar nikal aata hai raasta",
		"mita de apni hasti ko agar kuchh martaba chahe : ki dana khaak in mil kar gul-o-gulzar hota hai",
		"nahin hai na-ummid 'iqbal' apni kisht-e-virab se : zara nam ho to ye miTTi bahut zarkhez hai saaqi",
		"dil bedaar farda ka talashi ho jis dil in : voh dard de mujh ko kis qadar mahsus karta hai",
		"taqdir ke qaazi ka ye fatva hai azal se : hai jurm-e-zaeefi ki saza marg-e-mufaajat",
	},
	-- Bahadur Shah Zafar
	Bahadur_Shah_Zafar = {
		"lagta nahin hai dil ra ujDe dayar mein : kis ki bani hai aalam-e-na-paedar mein",
		"kah do in hasraton se kahin aur ja basen : itni jagah dil in kahan dard-e-ishq ke",
		"umr-e-daraz maang kar laaye the chaar din : do arzu in kaT gaye do intizar mein",
		"kitna hai bad-naseeb 'zafar' dafn ke liye : do gaz zaen bhi na mili ku-e-yar mein",
		"na the ham jab pa.e ja.ate the keh ham hain : hue jab ham to phir 'ham' kuchh nahin rahe",
		"din zindagi ke khatm hue shaam ho gayi : phaila ke pa.eb soyenge kaTi hai raat ji",
	},
	-- Momin Khan Momin
	Momin_Khan_Momin = {
		"tum mere paas hote ho goya : jab koi dusra nahin hota",
		"vo jo ham in tum mein qarar tha tumhen yaad ho ke na yaad ho : vahi yaani vaada nibah ka tumhen yaad ho ke na yaad ho",
		"Umr saari to kaTi ishq-e-butan men 'momin' : akhiri vaqt men kya khaak musalman honge",
		"is shokhi ki ho savari kya : kabhi puchha kabhi takrar nahin",
		"maiñ bhī kuchh ḳhush nahīñ vafā kar ke : tum ne achchhā kiyā nibāh na kī",
		"tum hamare kisi tarah na hue : varna duniya men kya nahin hota",
		"sharamate ho mil kar mujh se ai but : qasam khuda ki achchhi baat hai",
		"vo bhi din the ki ham se yar the ham : ab kisi baat par bhi yar nahin",
		"asar usko zara nahin hota : ranj raahat-fazaa nahin hota",
		"haal-e-dil yaar ko likhun kyunkar : haath dil se juda nahin hota",
		"kabhi hum mein tum mein bhi chah thi : kabhi hum se tum se bhi rah thi",
		"kabhi hum bhi tum bhi the aashna : tumhen yaad ho ke na yaad ho",
		"chaara-e-dil sivaae sabr nahin : so tumhaare sivaa nahin hota",
		"kyun sune arz-e-muztar ai momin : sanam aakhir khuda nahin hota",
	},
	-- Wali Mohammad Wali
	Wali_Mohammad_Wali = {
		"zulf-e-mushkin ko hila kar voh jo guzra sar-e-baam : kuufr ki bu mahkae gai sarv-qad-e-islam",
		"ji in ai but tira ya kufr basa hai ya islam : kabhi sajda kabhi but jaankaar karta hun",
		"charaagh-e-toor sa raushan hai harf-e-ham nasheen apna : khaTakta hai jo dil in so kahe dete hain bayan apna",
		"jise ishq ka tir kari lage : use zindagi kyun na bhaari lage",
		"muflisi sab bahaar khoti hai : mard ka e'tibaar khoti hai",
		"yaad karna har ghaDi tujh yaar ka : hai vazifa mujh dil-e-bimaar ka",
	},
}

return ashaar
