local ashaar = {
	Ghalib = {
		"ham ko ma.alūm hai jannat kī haqīqat lekin : dil ke khush rakhne ko 'ġhālib' ye khayāl achchhā hai",
		"karne ga.e the us se taghāful kā ham gila : kī ek hī nigāh ki bas khaak ho ga.e",
		"ishq ne 'ghalib' nikammā kar diyā : varna ham bhi aadmī the kaam ke",
		"is sādgī pe kaun na mar jaa.e ai khudā : laDte haiñ aur haath meñ talvār bhī nahīñ",
		"mohabbat meñ nahīñ hai farq jiine aur marne kā : usī ko dekh kar jiite haiñ jis kāfir pe dam nikle ",
		"maiñ bhī muñh meñ zabān rakhtā huuñ : kaash pūchho ki mudda.ā kyā hai",
		"hazāroñ khvāhisheñ aisī ki har ḳhvāhish pe dam nikle : bahut nikle mire armān lekin phir bhī kam nikle",
		"un ke dekhe se jo aa jaatī hai muñh par raunaq : vo samajhte haiñ ki bīmār kā haal achch hai",
		"ye na thī hamārī qismat ki visāl-e-yār hotā : agar aur jiite rahte yahī intizār hotā",
		"ragoñ meñ dauḌte phirne ke ham nahīñ qaa.il : jab aañkh hī se na Tapkā to phir lahū kyā hai",
		"ishq par zor nahīñ hai ye vo ātish 'ġhālib' : ki lagā.e na lage aur bujhā.e na bane",
		"vo aa.e ghar meñ hamāre ḳhudā kī qudrat hai : kabhī ham un ko kabhī apne ghar ko dekhte haiñ",
		"ishrat-e-qatra hai dariyā meñ fanā ho jaanā : dard kā had se guzarnā hai davā ho jaanā",
		"na thā kuchh to ḳhudā thā kuchh na hotā to ḳhudā hotā : Duboyā mujh ko hone ne na hotā maiñ to kyā hotā",
		"dil hī to hai na sañg-o-ḳhisht dard se bhar na aa.e kyuuñ : ro.eñge ham hazār baar koī hameñ satā.e kyuuñ",
		"bas-ki dushvār hai har kaam kā āsāñ honā : aadmī ko bhī muyassar nahīñ insāñ honā ",
		"be-khudī be-sabab nahīñ 'ghālib' : kuchh to hai jis kī parda-dārī hai",
		"rañj se khūgar huā insāñ to miT jaatā hai rañj : mushkileñ mujh par paḌīñ itnī ki āsāñ ho ga.iiñ",
		"ham ko un se vafā kī hai ummīd : jo nahīñ jānte vafā kyā hai",
		"haiñ aur bhī duniyā meñ sukhan-var bahut achchhe : kahte haiñ ki 'ġhālib' kā hai andāz-e-bayāñ aur",
		"rekhte ke tumhīñ ustād nahīñ ho 'ghālib' : kahte haiñ agle zamāne meñ koī 'mīr' bhī thā",
		"ā.īna kyuuñ na duuñ ki tamāshā kaheñ jise : aisā kahāñ se lā.ūñ ki tujh sā kaheñ jise",
		"ishq se tabī.at ne ziist kā mazā paayā : dard kī davā paa.ī dard-e-be-davā paayā",
	},
	Dagh = {
		"tumhārā dil mire dil ke barābar ho nahīñ saktā : vo shīsha ho nahīñ saktā ye patthar ho nahīñ saktā",
		"hazāroñ kaam mohabbat meñ haiñ maze ke 'dāgh' : jo log kuchh nahīñ karte kamāl karte haiñ",
		"vafā kareñge nibāheñge baat māneñge : tumheñ bhī yaad hai kuchh ye kalām kis kā thā",
		"sab log jidhar vo haiñ udhar dekh rahe haiñ : ham dekhne vāloñ kī nazar dekh rahe haiñ",
		"milāte ho usī ko khaak meñ jo dil se miltā hai : mirī jaañ chāhne vaalā baḌī mushkil se miltā hai",
		"aa.ina dekh ke kahte haiñ sañvarne vaale : aaj be-maut mareñge mire marne vaale",
		"hameñ hai shauq ki be-parda tum ko dekheñge : tumheñ hai sharm to āñkhoñ pe haath dhar lenā",
		"tumhārā hī mushtāq-e-dīdār hogā : gayā jaan se ik javāñ aate aate",
		"is nahīñ kā koī ilaaj nahīñ : roz kahte haiñ aap aaj nahīñ",
		"āshiqī se milegā ai zāhid : bandagī se khudā nahīñ miltā",
		"ghazab kiyā tire va.ade pe e'tibār kiyā : tamām raat qayāmat kā intizār kiyā",
		"lipaT jaate haiñ vo bijlī ke Dar se : ilāhī ye ghaTā do din to barse",
		"khuub parda hai ki chilman se lage baiThe haiñ : saaf chhupte bhī nahīñ sāmne aate bhī nahīñ",
		"le chalā jaan mirī ruuTh ke jaanā terā : aise aane se to behtar thā na aanā terā",
		"na jaanā ki duniyā se jaatā hai koī : bahut der kī mehrbāñ aate aate",
		"chale aate haiñ dil meñ armān lākhoñ : makāñ bhar gayā mehmāñ aate aate",
		"nahīñ khel ai 'dāġh' yāroñ se kah do : ki aatī hai urdu zabāñ aate aate",
	},
}

return ashaar
