local ashaar = {
	-- Dagh Dehlvi
	Dagh_Dehlavi = {
		"tumhara dil mire dil ke barabar ho nahin sakta : vo shisha ho nahi sakta ye patthar ho nahin sakta",
		"hazaron kaam mohabbat meb hain maze ke 'dagh' : jo log kuchh nahin karte kamal karte hain",
		"vafa karenge nibahebge baat manenge : tumhen bhi yaad hai kuchh ye kalam kis ka tha",
		"sab log jidhar vo hain udhar dekh rahe hain : ham dekhne valon ki nazar dekh rahe hain",
		"milate ho usi ko khaak men jo dil se milta hai : miri jaan chahne vaala baDi mushkil se milta hai",
		"aa.ina dekh ke kahte hain sabvarne vaale : aaj be-maut marenge mire marne vaale",
		"hamen hai shauq ki be-parda tum ko dekhebge : tumhen hai sharm to ankhon pe haath dhar lena",
		"tumhara hi mushtaq-e-didar hoga : gaya jaan se ik javan aate aate",
		"is nahin ka koi ilaaj nahi : roz kahte hain aap aaj nahin",
		"ashiqi se milega ai zahid : bandagi se khuda nahin milta",
		"ghazab kiya tire va.ade pe e'tibar kiya : tamam raat qayamat ka intizar kiya",
		"lipaT jaate hain vo bijli ke Dar se : ilahi ye ghaTa do din to barse",
		"khuub parda hai ki chilman se lage baiThe hain : saaf chhupte bhi nahi samne aate bhi nahin",
		"hijr men zahr kha ke mar ja.ub : maut ka intizar kaun kare",
		"le chala jaan miri ruuTh ke jaana tera : aise aane se to behtar tha na aana tera",
		"zid har ik baat par nahin achchhi : dost ki dost maan lete hain",
		"na jaana ki duniya se jaata hai koi : bahut der ki mehrban aate aate",
		"chale aate hain dil meb arman lakhon : makan bhar gaya mehman aate aate",
		"nahin khel ai 'dagh' yarob se kah do : ki aati hai urdu zaban aate aate",
		"shab-e-visal hai gul kar do in charaghon ko : khushi ki bazm meb kya kaam jalne valon ka",
		"aap ka e'tibar kaun kare : roz ka intizar kaun kare",
		"hazar baar jo manga karo to kya hasil : dua vahi hai jo dil se kabhi nikalti hai",
		"lutf-e-mai tujh se kya kahun zahid : haa.e kam-bakht tu ne pi hi nahi",
		"rukh-e-raushan ke aage sham.a rakh kar vo ye kahte hain : udhar jaata hai dekheb ya idhar parvana aata hai",
		"saqiya tishnagi ki taab nahin : zahr de de agar sharab nahi",
		"falak deta hai jin ko aish un ko gham bhi hote hain : jahab bajte hain naqqare vahan matam bhi hota hai",
		"tum ko chaha to khata kya hai bata do mujh ko : dusra koi to apna sa dikha do mujh ko",
	},
	-- Mirza Ghalib
	Ghalib = {
		"ham ko ma.alum hai jannat ki haqiqat lekin : dil ke khush rakhne ko 'ghalib' ye khayal achchha hai",
		"karne gaye the us se taghaful ka ham gila : ki ek hi nigah ki bas khaak ho gaye",
		"ishq ne 'ghalib' nikamma kar diya : varna ham bhi aadmi the kaam ke",
		"is sadgi pe kaun na mar jaa.e ai khuda : laDte hain aur haath meb talvar bhi nahin",
		"mohabbat men nahi hai farq jiine aur marne ka : usi ko dekh kar jiite hain jis kafir pe dam nikle ",
		"main bhi mubh men zaban rakhta huun : kaash puchho ki mudda.a kya hai",
		"hazaron khvahisheb aisi ki har khvahish pe dam nikle : bahut nikle mire arman lekin phir bhi kam nikle",
		"un ke dekhe se jo aa jaati hai munh par raunaq : vo samajhte hain ki bimar ka haal achch hai",
		"ye na thi hamari qismat ki visal-e-yar hota : agar aur jiite rahte yahi intizar hota",
		"ragon meb dauDte phirne ke ham nahin qaa.il : jab aankh hi se na Tapka to phir lahu kya hai",
		"ishq par zor nahin hai ye vo atish 'ghalib' : ki lagaye na lage aur bujha.e na bane",
		"vo aa.e ghar men hamare khuda ki qudrat hai : kabhi ham un ko kabhi apne ghar ko dekhte hain",
		"ishrat-e-qatra hai dariya men fana ho jaana : dard ka had se guzarna hai dava ho jaana",
		"na tha kuchh to khuda tha kuchh na hota to khuda hota : Duboya mujh ko hone ne na hota main to kya hota",
		"dil hi to hai na sang-o-khisht dard se bhar na aa.e kyuub : ro.enge ham hazaar baar koi hamen sata.e kyuun",
		"bas-ki dushvar hai har kaam ka asan hona : aadmi ko bhi muyassar nahi insan hona ",
		"be-khudi be-sabab nahin 'ghalib' : kuchh to hai jis ki parda-dari hai",
		"ranj se khugar hua insab to miT jaata hai ranj : mushkilen mujh par paDin itni ki asan ho ga.iin",
		"ham ko un se vafa ki hai ummid : jo nahin jante vafa kya hai",
		"hain aur bhi duniya mai sukhan-var bahut achchhe : kahte hain ki 'ghalib' ka hai andaz-e-bayan aur",
		"rekhte ke tumhin ustad nahi ho 'ghalib' : kahte hain agle zamane men koi 'mir' bhi tha",
		"aaeena kyuun na duun ki tamasha kahen jise : aisa kahan se la.un ki tujh sa kahen jise",
		"kyuun na cheekhun ki yaad karte hain : meri avaz gar nahin aati",
		"har ek baat pe kahte ho tum ki tu kya hai : tumhin kaho ki ye andaz-e-guftugu kya hai",
		"ishq se tabi.at ne ziist ka maza paaya : dard ki dava paa.i dard-e-be-dava paaya",
		"aah ko chahiye ik umr asar hote tak : kaun jiita hai tiri zulf ke sar hote tak",
		"maut ka ek din muayyan hai : niind kyuun raat bhar nahin aati",
		"ye rashk hai ki vo hota hai ham-sukhan tum se : vagarna khauf-e-bad-amozi-e-adu kya hai",
		"aage aati thi hal-e-dil pe hansi : ab kisi baat par nahin aati",
		"jala hai jism jahan dil bhi jal gaya hoga : kuredte ho jo ab raakh justuju kya hai",
		"ham ne maana ki taghaful na karoge lekin : khaak ho ja.enge ham tum ko khabar hote tak",
		"puchhte hain vo ki 'ghalib' kaun hai : koi batlao ki ham batla.en kya",
		"dost ġham-khvāri men meri sa.i farmāvenge kyā : zakhm ke bharte talak nākhun na baḌh jāvenge kyā",
		"khāna-zād-e-zulf hain zanjir se bhāgenge kyuun : hain giraftār-e-vafā zindān se ghabrāvenge kyā",
		"ye kahan ki dosti hai ki bane hain dost naseh : koi charasaz hota koi gham-gusar hota",
		"ragon men dauḌte phirne ke ham nahin qaa.il : jab aankh hi se na Tapka to phir lahu kya hai",
		"kaaba kis munh se jaoge 'ghalib' : sharm tum ko magar nahin aati",
	},
	-- Meer Taqi Meer
	Meer = {
		"rah-e-dur-e-ishq men rota hai kya : aage aage dekhiye hota hai kya",
		"patta patta buuTa buuTa haal hamara jaane hai : jaane na jaane gul hi na jaane baagh to saara jaane hai",
		"hoga kisi divar ke saa.e men paDa 'mir' : kya rabt mohabbat se us aram-talab ko",
		"mat sahl hamen jaano phirta hai falak barsob : tab khaak ke parde se insan nikalte hain",
		"nazuki us ke lab ki kya kahiye : pankhuDi ik gulab ki si hai",
		"'mir' ham mil ke bahut khush hue tum se pyare : is kharabe meb miri jaan tum abad raho",
		"ahd-e-javani ro ro kaaTa piiri meb li ankhein muund : yaani raat bahut the jaage subah hui aram kiya",
		"mujhe kaam rone se aksar hai naseh : tu kab tak mire mubh ko dhota rahega",
		"'mir' un nim-baz abkhon men : saari masti sharab ki si hai",
		"ishq ik 'mir' bhari patthar hai : kab ye tujh na-tavan se uThta hai",
		"shaam se kuchh bujha sa rahta huun : dil hua hai charagh muflis ka",
		"dekh to dil ki jaab se uThta hai : ye ddhua sa kahan se uThta hai",
		"kaash us ke ru-ba-ru na kareb mujh ko hashr mein : kitne mire saval hain jin ka nahin javab",
		"ishq men ji ko sabr-o-taab kahab : uss se ankhein laDin to khvab kahan",
		"padhte phirebge galiyon men in rekhton ko log : muddat rahengi yaad ye baten hamariyan",
		"'mir' bandon se kaam kab nikla : mangna hai jo kuchh khuda se maang",
		"tujh ko masjid hai mujh ko mai-khana : vaaiyz apni apni qismat hai",
		"tha sab ko da.ava ishq ka lekin na Thahra koi bhi : danista apni jaan se dil ko uThaya ek maib",
		"'mir' sahab tum farishta ho to ho : aadmi hona to mushkil hai miyan",
		"yahi jaana ki kuchh na jaana haa.e : so bhi ik umr mein hua ma`lum",
		"jaise bijli ke chamakne se kisi ki sudh jaae : be-khudi aa.i achanak tire aa jaane se",
		"surma jo nuur bakhshe hai abkhon ko khalq ki : shayad ki rah-e-yar ki hi khaak dhuul ho",
		"kaam the ishq meb bahut par 'mir' : ham hi farigh hue shitabi se",
		"hosh jaata nahin raha lekin : jab vo aata hai tab nahin aata",
		"dilli men aaj bhiik bhi milti nahi unhen : tha kal talak dimagh jinhen taj-o-takht ka",
		"ab jo ik hasrat-e-javani hai : umr-e-rafta ki ye nishani hai",
		"umr guzri dava.en karte 'mir' : dard-e-dil ka hua na chara hanuz",
		"tadbir mere ishq ki kya fa.eda tabib : ab jaan hi ke saath ye azar ja.ega",
		"bulbul ghazal-sara.i aage hamare mat kar : sab ham se sikhte hain andaz guftugu ka",
		"dil vo nagar nahin ki phir abad ho sake pachhtaoge suno ho ye basti ujaaD kar",
		"jab ki pahlu se yaar uThta hai : dard be-ikhtiyar uThta hai",
		"hazar martaba behtar hai badshahi se : agar nasib tire kuche ki gada.i ho",
		"ham jante to ishq na karte kisu ke saath : le jaate dil ko khaak men is aarzu ke saath",
		"guftugu rekhte men ham se na kar : ye hamari zaban hai pyare",
		"tujhi par kuchh ai but nahin munhasir : jise ham ne puuja khuda kar diya",
		"yuun uThe aah us gali se ham : jaise koi jahan se uThta hai",

		"jin jin ko tha ye ishq ka azar mar gaye : aksar hamare saath ke bimar mar gaye",
	},
	-- Parveen Shakir
	Parveen_Shakir = {
		"vo na aaega hamen ma.alum tha is shaam bhi : intizar us ka magar kuchh soch kar karte rahe",
		"kuchh to hava bhi sard thi kuchh tha tira khayal bh : dil ko khushi ke saath saath hota raha malal bhi",
		"meri talab tha ek shakhs vo jo nahin mila to phir : haath dua se yuun gira bhuul gaya saval bhi",
		"ghar aap hi jagmaga uThega : dahliz pe ik qadam bahut hai",
		"ye hava kaise uDa le gai anchal mera : yuun satane ki to aadat mire ghanshyam ki thi",
		"sukuut-e-shahr-e-sukhan men vo phuul sa lahja : samaaton ki faza khvab khvab kar dega",
		"shaam ki na-samajh hava puchh rahi hai ik pata : mauj-e-hava-e-ku-e-yar kuchh to mira khayal bhi",
		"kaanp uThti huun main ye soch ke tanhai men : mere chehre pe tira naam na paDh le koi",
		"kuchh to tire mausam hi mujhe raas kam aae : aur kuchh miri miTTi men baghavat bhi bahut thi",
		"baat vo aadhi raat ki raat vo puure chand ki : chand bhi ain chait ka us pe tira jamal bhi",
		"husn ke samajhne ko umr chahiye janan : do ghaDi ki chahat men laDkiyan nahin khultin",
		"raste men mil gaya to sharik-e-safar na jaan : jo chhanv mehrban ho use apna ghar na jaan",
		"vo to khush-bu hai havao meb bikhar jaega : masla phool ka hai phuul kidhar jaega",
		"kuchh faisla to ho ki kidhar jaana chahiye : paani ko ab to sar se guzar jaana chahiye",
		"kaise kah duun ki mujhe chhoD diya hai us ne : baat to sach hai magar baat hai rusvai ki",
		"aks-e-khushbu huun bikharne se na roke koi : aur bikhar jaun to mujh ko na sameTe koi",
		"apne qatil ki zehanat se pareshan huun main : roz ik maut naye tarz ki ijad kare",
		"main sach kahungi magar phir bhi haar jaungi : wo jhuT bolega aur la-jawab kar dega",
		"dene vaale ki mashiyyat pe hai sab kuchh mauquf : mangne vaale ki hajat nahin dekhi jaati",
		"mumkina faislon men ek hijr ka faisla bhi tha : ham ne to ek baat ki us ne kamal kar diya",
		"haath mere bhuul baiThe dastaken dene ka fan : band mujh par jab se us ke ghar ka darvaza hua",
		"vaqt-e-rukhsat aa gaya dil phir bhi ghabraya nahin : us ko ham kya kho.enge jis ko kabhi paaya nahin",
		"tere paimane men gardish nahin baaqi saaqi : aur tiri bazm se ab koi uTha chahta hai",
		"tere tohfe to sab achchhe hain magar mauj-e-bahar : ab ke mere liye khushbu-e-hina aai ho",
		"yuuñ dekhnā us ko ki koī aur na dekhe : in.aam to achchhā thā magar shart kaḌī thī",
		"pā-ba-gil sab haiñ rihā.ī kī kare tadbīr kaun : dast-basta shahr meñ khole mirī zanjīr kaun",
	},
	-- Jaun Eliya
	Jaun_Eliya = {
		"bahut nazdik aati ja rahi ho : bichhaDne ka irada kar liya kya",
		"shaam hi se dukan-e-did hai band : nahin nuqsan tak dukan men kya",
		"yaaro kuchh to zikr karo tum us ki qayamat banhon ka : vo jo simaTte honge un men vo to mar jaate honge",
		"umr guzregi imtihan men kya : daagh hi denge mujh ko daan men kya",
		"meri har baat be-asar hi rahi : nuqs hai kuchh mire bayan men kya",
		"aur to kya tha bechne ke liye : apni ankhon ke khvab beche hain",
		"vo mile to ye puchhna hai mujhe : ab bhi huun main tiri amaan men kya",
		"main bhi bahut ajiib huun itna ajiib huun ki bas : khud ko tabah kar liya aur malal bhi nahin",
		"kya sitam hai ki ab tiri surat : ghaur karne pe yaad aati hai ",
		"kis liye dekhti ho a.ina : tum to khud se bhi khubsurat ho",
		"yuun jo takta hai asman ko tu : koi rahta hai asman men kya",
		"mustaqil bolta hi rahta huun : kitna khamosh huun main andar se",
		"us gali ne ye sun ke sabr kiya : jaane vaale yahan ke the hi nahin",
		"aaj mujh ko bahut bura kah kar : aap ne naam to liya mera",
		"jurm men ham kami karen bhi to kyuun : tum saza bhi to kam nahin karte",
		"tumhara hijr mana luun agar ijazat ho : main dil kisi se laga luun agar ijazat ho",
		"bin tumhare kabhi nahin aa.i : kya miri niind bhi tumhari hai",
		"sochta huun ki us ki yaad akhir : ab kise raat bhar jagati hai",
		"zindagi kya hai ik kahani hai : ye kahani nahin sunani hai",
		"zindagi ek fan hai lamhon ko : apne andaz se ganvane ka",
		"ab miri koi zindagi hi nahin : ab bhi tum meri zindagi ho kya",
		"naya ik rishta paida kyuun karen ham : bichhaDna hai to jhagDa kyuun karen ham",
		"kaam ki baat main ne ki hi nahin : ye mira taur-e-zindagi hi nahin",
		"shauq hai is dil-e-darinda ko : aap ke honT kaaT khane ka",
		"apne sar ik bala to leni thi : main ne vo zulf apne sar li hai",
		"mil rahi ho baDe tapak ke saath : mujh ko yaksar bhula chuki ho kya",
	},
}

return ashaar
